name: Build and Release Package

on:
  push:
    branches:
      - main
    paths:
      - package.json

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
      id-token: write

    steps:
      - uses: oven-sh/setup-bun@v1

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        if: steps.check.outputs.changed == 'true'
        with:
          node-version: '20'

      - name: Install Dependencies

        if: steps.check.outputs.changed == 'true'
        run: bun install

      - name: Build Package
        if: steps.check.outputs.changed == 'true'
        run: bun build:package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        if: steps.check.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.check.outputs.version}}
          release_name: v${{steps.check.outputs.version}}
          draft: false
          prerelease: false

      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        if: steps.check.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path-js-${{steps.check.outputs.version}}.tgz
          asset_name: path-js-${{steps.check.outputs.version}}.tgz
          asset_content_type: application/gzip
